### ISSUE TITLE
Add docstring for all function arguments in Pyaqueduct

### ISSUE THREAD

**Issue by samiralavi** [AqueductHub/pyaqueduct#11]
As a user, I want to have the information needed to write an experiment which I might need to know what arguments are.

for example, in find_experiments function, I want to know what limit is and what's the type.

**Comment by jatinriverlane** [comment]
While working on it, I noticed that we do not support tags parameter in `create_experiment` method in `API` class in `api.py`. 

Is this intended @samiralavi  ?
