### ISSUE TITLE
Refactor user input non-type validation to rely on server

### ISSUE THREAD

**Issue by samiralavi** [AqueductHub/pyaqueduct#24]
Now the server can validate user input, it is better to remove duplicated code for non-type validation of user input such as the length and format of strings.  Not only does it avoid code duplication, but also it lets the server change the constraints without the need to change the code.

**Comment by tomhartley** [comment]
Can you share some examples of how this will impact the end user experience (if at all)?

**Comment by samiralavi** [comment]
It doesn't affect the user experience. It is a technical dept. We are doing validation two times against duplicated constraints in two places. If in future we want to change the constraints, such as tag length, we have to do it two times and release both PyAqueduct and Aqueduct for that, which is not right.
